import { getActiveLang } from '@/lib/i18n';

export type UiLang = 'en' | 'zh-CN';
export type UiKey = string;

type Dict = Record<UiLang, Record<UiKey, string>>;

const DICT: Dict = {
  en: {
    // Common
    'common.loading': 'Loading...',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.copy': 'Copy',
    'common.hide_now': 'Hide Now',
    'common.confirm': 'Confirm',
    'common.back': 'Back',

    // Sidebar
    'nav.dashboard': 'Dashboard',
    'nav.transfer': 'Transfer',
    'nav.settings': 'Settings',
    'nav.create': 'Create',
    'nav.import': 'Import',
    'nav.lock_wallet': 'Lock Wallet',

    // Password dialog
    'pw.unlock_wallet': 'Unlock Wallet',
    'pw.enter_wallet_password': 'Enter wallet password',
    'pw.unlock': 'Unlock',
    'pw.invalid_password': 'Invalid password',

    // Settings
    'settings.title': 'Settings',
    'settings.security': 'Security',
    'settings.export_mnemonic': 'Export Mnemonic',
    'settings.view_recovery_phrase': 'View your recovery phrase',
    'settings.change_password': 'Change Password',
    'settings.update_wallet_password': 'Update wallet encryption password',
    'settings.export_wallet_json': 'Export wallet.json',
    'settings.download_encrypted_wallet_file': 'Download encrypted wallet file',
    'settings.mnemonic_phrase': 'Mnemonic Phrase',
    'settings.auto_hide_in': 'Auto-hide in',
    'settings.new_password': 'New Password',
    'settings.confirm_new_password': 'Confirm New Password',
    'settings.update_password': 'Update Password',
    'settings.at_least_8': 'At least 8 characters',
    'settings.repeat_new_password': 'Repeat new password',
    'settings.danger_zone': 'Danger Zone',
    'settings.remove_wallet': 'Remove Wallet',
    'settings.yes_remove': 'Yes, Remove',
    'settings.select_wallet_first': 'Select a wallet first.',
    'settings.remove_wallet_warning': 'This removes the wallet from this browser. Make sure you have your mnemonic backup!',
    'settings.enter_password_to_export_mnemonic': 'Enter password to export mnemonic',
    'settings.enter_current_password': 'Enter current password',
    'toast.wallet_unlocked': 'Wallet unlocked',
    'toast.password_updated': 'Password updated',
    'toast.wallet_renamed': 'Wallet renamed',
    'toast.wallet_removed': 'Wallet removed',
    'toast.wallet_json_exported': 'wallet.json exported',
    'toast.mnemonic_copied': 'Mnemonic copied to clipboard',

    // Send
    'send.title': 'Send ALICE',
    'send.transfer_sent': 'Transfer Sent!',
    'send.transaction_hash': 'Transaction Hash:',
    'send.send_another': 'Send Another',
    'send.available': 'Available:',
    'send.recipient_address': 'Recipient Address',
    'send.amount': 'Amount (ALICE)',
    'send.sending': 'Sending...',
    'send.send': 'Send',
    'send.enter_recipient': 'Enter recipient address',
    'send.enter_valid_amount': 'Enter a valid amount',
    'send.transfer_sent_toast': 'Transfer sent!',
    'send.transfer_failed': 'Transfer failed',

    // History
    'history.title': 'Transaction History',
    'history.no_transactions': 'No transactions found',
    'history.sent': 'Sent',
    'history.received': 'Received',
    'history.success': 'Success',
    'history.failed': 'Failed',
    'history.to': 'To:',
    'history.from': 'From:',
    'history.block': 'Block #',
    'history.load_more': 'Load More',

    // Staking
    'staking.title': 'Staking',
    'staking.balance': 'Balance',
    'staking.scorer': 'Scorer',
    'staking.aggregator': 'Aggregator',
    'staking.unstake': 'Unstake',
    'staking.not_staked': 'Not staked',
    'staking.stake_alice': 'Stake ALICE',
    'staking.amount': 'Amount (ALICE)',
    'staking.service_endpoint': 'Service Endpoint',
    'staking.stake_as_role': 'Stake as {role}',
    'staking.enter_valid_amount': 'Enter a valid amount',
    'staking.enter_endpoint': 'Enter your service endpoint',
    'staking.wallet_unlocked': 'Wallet unlocked',
    'staking.stake_failed': 'Stake failed',
    'staking.unstake_failed': 'Unstake failed',
    'staking.staked_success': 'Staked {amount} ALICE as {role}',
    'staking.unstake_started': 'Unstake cooldown started ({role})',

    // Dashboard
    'dashboard.welcome_title': 'Welcome to Alice Wallet',
    'dashboard.welcome_desc': 'Create a new wallet or import an existing one to get started with Alice Protocol.',
    'dashboard.create_wallet': 'Create Wallet',
    'dashboard.import': 'Import',
    'dashboard.select_wallet': 'Select a wallet from the sidebar.',
    'dashboard.balance': 'Balance',
    'dashboard.failed_load_balance': 'Failed to load balance',
    'dashboard.send': 'Send',
    'dashboard.transfer_alice': 'Transfer ALICE',
    'dashboard.transactions': 'Transactions',
    'dashboard.loading_transactions': 'Loading transactions...',
    'dashboard.failed_load_transactions': 'Failed to load transactions',

    // Create
    'create.title': 'Create New Wallet',
    'create.step.name': 'Name',
    'create.step.backup': 'Backup',
    'create.step.verify': 'Verify',
    'create.step.password': 'Password',
    'create.wallet_name': 'Wallet Name',
    'create.wallet_name_desc': 'Give your wallet a name to identify it easily.',
    'create.wallet_name_placeholder': 'e.g. My Wallet, Mining Wallet...',
    'create.enter_wallet_name': 'Please enter a wallet name',
    'create.generate_mnemonic': 'Generate Mnemonic',
    'create.failed_generate_mnemonic': 'Failed to generate mnemonic',
    'create.write_down_title': 'Write down these 24 words IN ORDER',
    'create.write_down_desc': 'This is the ONLY way to recover your wallet. Never save digitally. Never share.',
    'create.your_mnemonic': 'Your Mnemonic',
    'create.address': 'Address:',
    'create.saved_mnemonic': 'I have saved my mnemonic',
    'create.verify_backup': 'Verify Your Backup',
    'create.verify_backup_desc': 'Enter the following words from your mnemonic to confirm you saved them.',
    'create.word_number': 'Word #{num}',
    'create.enter_word_number': 'Enter word #{num}',
    'create.word_incorrect': 'Word #{num} is incorrect',
    'create.verify': 'Verify',
    'create.set_password': 'Set Password',
    'create.password_encrypt_desc': 'This password encrypts your wallet locally. Min 8 characters.',
    'create.password': 'Password',
    'create.confirm_password': 'Confirm Password',
    'create.password_min_8': 'Password must be at least 8 characters',
    'create.passwords_no_match': 'Passwords do not match',
    'create.create_wallet': 'Create Wallet',
    'create.wallet_created': 'Wallet Created!',
    'create.redirecting': 'Redirecting to dashboard...',
    'toast.wallet_created': 'Wallet created successfully!',

    // Import
    'import.title': 'Import Wallet',
    'import.mnemonic_phrase': 'Mnemonic Phrase',
    'import.mnemonic_desc': 'Import using 12/24 word recovery phrase',
    'import.wallet_json_file': 'wallet.json File',
    'import.wallet_json_desc': 'Import an existing encrypted wallet file',
    'import.import_from_mnemonic': 'Import from Mnemonic',
    'import.import_from_wallet_json': 'Import from wallet.json',
    'import.wallet_name': 'Wallet Name',
    'import.wallet_name_placeholder': 'e.g. Imported Wallet',
    'import.enter_wallet_name': 'Enter a wallet name',
    'import.mnemonic_input': 'Mnemonic Phrase',
    'import.mnemonic_placeholder': 'Enter your recovery words separated by spaces...',
    'import.invalid_mnemonic': 'Invalid mnemonic. Enter valid BIP39 words (12/15/18/21/24).',
    'import.failed_derive_address': 'Failed to derive address',
    'import.validate_show_address': 'Validate & Show Address',
    'import.address': 'Address:',
    'import.password': 'Password',
    'import.confirm_password': 'Confirm Password',
    'import.import_wallet': 'Import Wallet',
    'toast.wallet_imported': 'Wallet imported!',
    'import.only_v2_supported': 'Only v2 wallet files are supported. Legacy wallets need migration via CLI first.',
    'import.click_select_wallet_json': 'Click to select wallet.json file',
    'import.wallet_password': 'Wallet Password',
    'import.enter_wallet_password': 'Enter the wallet password',
    'import.verify': 'Verify',
    'import.password_verified_ready': 'Password verified. Ready to import.',
    'import.invalid_password_or_corrupt': 'Invalid password or corrupted wallet file',
    'import.failed_parse_json': 'Failed to parse JSON file',
    'import.invalid_wallet_json_format': 'Invalid wallet.json format. Only version 2 wallets are supported.',
  },
  'zh-CN': {
    // Common
    'common.loading': '加载中…',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.copy': '复制',
    'common.hide_now': '立即隐藏',
    'common.confirm': '确认',
    'common.back': '返回',

    // Sidebar
    'nav.dashboard': '首页',
    'nav.transfer': '发送',
    'nav.settings': '设置',
    'nav.create': '新建',
    'nav.import': '导入',
    'nav.lock_wallet': '锁定钱包',

    // Password dialog
    'pw.unlock_wallet': '解锁钱包',
    'pw.enter_wallet_password': '请输入钱包密码',
    'pw.unlock': '解锁',
    'pw.invalid_password': '密码错误',

    // Settings
    'settings.title': '设置',
    'settings.security': '安全',
    'settings.export_mnemonic': '导出助记词',
    'settings.view_recovery_phrase': '查看恢复助记词',
    'settings.change_password': '修改密码',
    'settings.update_wallet_password': '更新钱包加密密码',
    'settings.export_wallet_json': '导出 wallet.json',
    'settings.download_encrypted_wallet_file': '下载加密的钱包文件',
    'settings.mnemonic_phrase': '助记词',
    'settings.auto_hide_in': '自动隐藏',
    'settings.new_password': '新密码',
    'settings.confirm_new_password': '确认新密码',
    'settings.update_password': '更新密码',
    'settings.at_least_8': '至少 8 个字符',
    'settings.repeat_new_password': '再次输入新密码',
    'settings.danger_zone': '危险操作',
    'settings.remove_wallet': '删除钱包',
    'settings.yes_remove': '确认删除',
    'settings.select_wallet_first': '请先选择一个钱包。',
    'settings.remove_wallet_warning': '这会从当前浏览器删除该钱包，请确保你已备份助记词！',
    'settings.enter_password_to_export_mnemonic': '输入密码以导出助记词',
    'settings.enter_current_password': '输入当前密码',
    'toast.wallet_unlocked': '钱包已解锁',
    'toast.password_updated': '密码已更新',
    'toast.wallet_renamed': '钱包已重命名',
    'toast.wallet_removed': '钱包已删除',
    'toast.wallet_json_exported': '已导出 wallet.json',
    'toast.mnemonic_copied': '助记词已复制到剪贴板',

    // Send
    'send.title': '发送 ALICE',
    'send.transfer_sent': '转账已发送！',
    'send.transaction_hash': '交易哈希：',
    'send.send_another': '继续转账',
    'send.available': '可用余额：',
    'send.recipient_address': '收款地址',
    'send.amount': '金额（ALICE）',
    'send.sending': '发送中…',
    'send.send': '发送',
    'send.enter_recipient': '请输入收款地址',
    'send.enter_valid_amount': '请输入正确的金额',
    'send.transfer_sent_toast': '转账已发送！',
    'send.transfer_failed': '转账失败',

    // History
    'history.title': '交易记录',
    'history.no_transactions': '暂无交易记录',
    'history.sent': '转出',
    'history.received': '转入',
    'history.success': '成功',
    'history.failed': '失败',
    'history.to': '发送到：',
    'history.from': '来自：',
    'history.block': '区块 #',
    'history.load_more': '加载更多',

    // Staking
    'staking.title': '质押',
    'staking.balance': '余额',
    'staking.scorer': 'Scorer',
    'staking.aggregator': 'Aggregator',
    'staking.unstake': '解除质押',
    'staking.not_staked': '未质押',
    'staking.stake_alice': '质押 ALICE',
    'staking.amount': '金额（ALICE）',
    'staking.service_endpoint': '服务地址',
    'staking.stake_as_role': '以 {role} 身份质押',
    'staking.enter_valid_amount': '请输入正确的金额',
    'staking.enter_endpoint': '请输入你的服务地址',
    'staking.wallet_unlocked': '钱包已解锁',
    'staking.stake_failed': '质押失败',
    'staking.unstake_failed': '解除质押失败',
    'staking.staked_success': '已质押 {amount} ALICE（{role}）',
    'staking.unstake_started': '已开始解除质押冷却（{role}）',

    // Dashboard
    'dashboard.welcome_title': '欢迎使用 Alice 钱包',
    'dashboard.welcome_desc': '创建新钱包或导入已有钱包，即可开始使用 Alice Protocol。',
    'dashboard.create_wallet': '新建钱包',
    'dashboard.import': '导入',
    'dashboard.select_wallet': '请在左侧选择一个钱包。',
    'dashboard.balance': '余额',
    'dashboard.failed_load_balance': '余额加载失败',
    'dashboard.send': '发送',
    'dashboard.transfer_alice': '发送 ALICE',
    'dashboard.transactions': '交易记录',
    'dashboard.loading_transactions': '正在加载交易记录…',
    'dashboard.failed_load_transactions': '交易记录加载失败',

    // Create
    'create.title': '新建钱包',
    'create.step.name': '命名',
    'create.step.backup': '备份',
    'create.step.verify': '验证',
    'create.step.password': '密码',
    'create.wallet_name': '钱包名称',
    'create.wallet_name_desc': '为钱包取个名字，方便识别。',
    'create.wallet_name_placeholder': '例如：我的钱包、矿机钱包…',
    'create.enter_wallet_name': '请输入钱包名称',
    'create.generate_mnemonic': '生成助记词',
    'create.failed_generate_mnemonic': '生成助记词失败',
    'create.write_down_title': '请按顺序抄写这 24 个单词',
    'create.write_down_desc': '这是找回钱包的唯一方式。不要以电子方式保存，不要分享给任何人。',
    'create.your_mnemonic': '你的助记词',
    'create.address': '地址：',
    'create.saved_mnemonic': '我已保存助记词',
    'create.verify_backup': '验证备份',
    'create.verify_backup_desc': '请输入指定序号的单词，确认你已正确保存助记词。',
    'create.word_number': '第 {num} 个单词',
    'create.enter_word_number': '请输入第 {num} 个单词',
    'create.word_incorrect': '第 {num} 个单词不正确',
    'create.verify': '验证',
    'create.set_password': '设置密码',
    'create.password_encrypt_desc': '该密码仅用于本地加密钱包。至少 8 个字符。',
    'create.password': '密码',
    'create.confirm_password': '确认密码',
    'create.password_min_8': '密码至少 8 个字符',
    'create.passwords_no_match': '两次输入的密码不一致',
    'create.create_wallet': '创建钱包',
    'create.wallet_created': '钱包创建成功！',
    'create.redirecting': '即将跳转到首页…',
    'toast.wallet_created': '钱包创建成功！',

    // Import
    'import.title': '导入钱包',
    'import.mnemonic_phrase': '助记词',
    'import.mnemonic_desc': '使用 12/24 个助记词导入钱包',
    'import.wallet_json_file': 'wallet.json 文件',
    'import.wallet_json_desc': '导入已加密的钱包文件',
    'import.import_from_mnemonic': '通过助记词导入',
    'import.import_from_wallet_json': '通过 wallet.json 导入',
    'import.wallet_name': '钱包名称',
    'import.wallet_name_placeholder': '例如：导入的钱包',
    'import.enter_wallet_name': '请输入钱包名称',
    'import.mnemonic_input': '助记词',
    'import.mnemonic_placeholder': '请输入助记词（空格分隔）…',
    'import.invalid_mnemonic': '助记词无效。请输入有效的 BIP39 助记词（12/15/18/21/24）。',
    'import.failed_derive_address': '地址解析失败',
    'import.validate_show_address': '校验并显示地址',
    'import.address': '地址：',
    'import.password': '密码',
    'import.confirm_password': '确认密码',
    'import.import_wallet': '导入',
    'toast.wallet_imported': '导入成功！',
    'import.only_v2_supported': '仅支持 v2 版本钱包文件。旧版本钱包需要先通过 CLI 迁移。',
    'import.click_select_wallet_json': '点击选择 wallet.json 文件',
    'import.wallet_password': '钱包密码',
    'import.enter_wallet_password': '请输入钱包密码',
    'import.verify': '验证',
    'import.password_verified_ready': '密码验证通过，可以导入。',
    'import.invalid_password_or_corrupt': '密码错误或钱包文件已损坏',
    'import.failed_parse_json': '解析 JSON 文件失败',
    'import.invalid_wallet_json_format': 'wallet.json 格式无效，仅支持 v2 钱包',
  },
};

export function uiLangFromPathname(pathname: string): UiLang {
  return getActiveLang(pathname);
}

export function uiText(lang: UiLang, key: UiKey, vars?: Record<string, string | number>): string {
  const tpl = DICT[lang][key] ?? DICT.en[key] ?? key;
  if (!vars) return tpl;
  return tpl.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? `{${k}}`));
}
